#!/usr/bin/env php
<?php

require("packages/autoload.php");

use Strukt\Event\Event;
use Strukt\Core\Map;
use Strukt\Core\Collection;
use Strukt\Fs;
use Strukt\Process\Process;

$_SERVER["map"] = new Map(new Collection());

function go($name){

    if(!$_SERVER["map"]->exists($name))
        exit(sprintf("Command %s does not exists!", $name));

    return $_SERVER["map"]->get($name)->exec();   
}

function watch($dir, \Closure $callback, $wait=1){

    $currHash = null;
    $prevHash = null;

    $currPaths = [];
    $prevPaths = [];

    $evt = Strukt\Event\Event::newEvent($callback);

    while(true){

        clearstatcache();
        sleep($wait);

        if(Strukt\Fs::isFile($dir))
            $files[] = $dir;
        else if(Strukt\Fs::isPath($dir))
            $files = Strukt\Fs::lsr($dir);
        else
            exit("Unknown file or path!");

        while($path = current($files)){

            $currPaths[$path] = md5_file($path);

            if(empty(next($files)))
                break;
        }

        $currHash = md5(implode("", $currPaths));

        $diffPaths = array_keys(array_diff($currPaths, $prevPaths));

        if($currHash!=$prevHash && !is_null($prevHash))
            $evt->apply($diffPaths)->exec();

        $prevHash = $currHash;
        $prevPaths = $currPaths;
    }
}

function task($name, Closure $func){

	if($_SERVER["map"]->exists($name))
		exit(sprintf("Command [%s] already exists!\n", $name));

	$_SERVER["cmdList"][] = $name;
    $_SERVER["map"]->set($name, Event::newEvent($func));
}

function writeln($line){

    echo sprintf("%s\n", $line);
}

function run($cmd, $callback = null, $input = null){

	$process = Process::run($cmd, $callback);

	if(!is_null($input)){

		$process->write($input);
		$process->closeInput();
	}

	return array(

		$process->read(),
		$process->error(),
	);
}

if(!Strukt\Fs::isFile("tasker.php"))
	Strukt\Fs::touchWrite("tasker.php", 
"<?php
task('test', function(){
    
    writeln('Hello world');
});");

task("version", function(){

	echo(sprintf("\n %s\n\n", "Tasker v1.0.0-alpha"));
});

task("list", function(){

	exit(sprintf("\n%s\n\n", implode("\n", array_map(function($cmd){

		return sprintf(" %s", $cmd);

	}, $_SERVER["cmdList"]))));
});

include("tasker.php");

$cmd = next($_SERVER["argv"]);

if(!empty($cmd))
	if(in_array($cmd, $_SERVER["cmdList"]))
		$_SERVER["map"]->get($cmd)->exec();
	else
		exit("Tasker could not find command!\n");
else
	exit("No command indicated!\n");